services:
  scrapper:
    build: .
    container_name: scrapper
    restart: always
    command: python3 app/scrapper.py
    volumes:
      - ./data:/app

  ai_processor:
    build: .
    container_name: ai_processor
    restart: always
    command: python3 app/ai_processor.py
    volumes:
      - ./data:/app
    env_file:
      - .env
    networks:
      - ollama_network

  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    command: python3 app/telegram_bot.py
    volumes:
      - ./data:/app
    env_file:
      - .env

networks:
  ollama_network:
    external: true

